// ─── INSTITUTES ────────────────────────────────────────────────────────────
export const institutes = [
  { id: 1, name: "Aadya Institute" },
  { id: 2, name: "PES College of Engineering" },
  { id: 3, name: "Oxford College of Engineering" },
  { id: 4, name: "BMS College of Engineering" },
  { id: 5, name: "RV College of Engineering" },
  { id: 6, name: "Other" },
];

// ─── COMPANIES ─────────────────────────────────────────────────────────────
export const companies = [
  {
    id: 1,
    name: "TechNova Solutions",
    industry: "IT Services",
    website: "https://technova.com",
    logo: "https://ui-avatars.com/api/?name=TechNova&background=0F4C81&color=fff&size=80",
    hrName: "Priya Sharma",
    hrEmail: "priya@technova.com",
    phone: "9876543210",
    openings: 15,
    status: "Active",
  },
  {
    id: 2,
    name: "Infosys Limited",
    industry: "IT Consulting",
    website: "https://infosys.com",
    logo: "https://ui-avatars.com/api/?name=Infosys&background=1E88E5&color=fff&size=80",
    hrName: "Rahul Nair",
    hrEmail: "rahul@infosys.com",
    phone: "9123456789",
    openings: 50,
    status: "Active",
  },
  {
    id: 3,
    name: "Wipro Technologies",
    industry: "IT Services",
    website: "https://wipro.com",
    logo: "https://ui-avatars.com/api/?name=Wipro&background=2E7D32&color=fff&size=80",
    hrName: "Anjali Mehta",
    hrEmail: "anjali@wipro.com",
    phone: "9988776655",
    openings: 30,
    status: "Active",
  },
  {
    id: 4,
    name: "HCL Technologies",
    industry: "Technology",
    website: "https://hcl.com",
    logo: "https://ui-avatars.com/api/?name=HCL&background=F9A825&color=fff&size=80",
    hrName: "Suresh Kumar",
    hrEmail: "suresh@hcl.com",
    phone: "9871234560",
    openings: 25,
    status: "Active",
  },
  {
    id: 5,
    name: "Capgemini India",
    industry: "IT Consulting",
    website: "https://capgemini.com",
    logo: "https://ui-avatars.com/api/?name=Capgemini&background=D32F2F&color=fff&size=80",
    hrName: "Neha Gupta",
    hrEmail: "neha@capgemini.com",
    phone: "9001234567",
    openings: 20,
    status: "Active",
  },
];

// ─── JOBS ───────────────────────────────────────────────────────────────────
export const jobs = [
  {
    id: 1,
    title: "Software Developer",
    company: "TechNova Solutions",
    companyId: 1,
    companyLogo: "https://ui-avatars.com/api/?name=TechNova&background=0F4C81&color=fff&size=80",
    location: "Bangalore",
    salary: "6–8 LPA",
    experience: "0–2 Years",
    lastDate: "2026-07-30",
    postedDate: "2026-07-01",
    status: "Published",
    skills: ["React", "Node.js", "MongoDB"],
    eligibility: "B.E / B.Tech – CS, IS, ECE – 60% and above",
    description:
      "We are looking for a passionate Software Developer to join our team. You will be responsible for building and maintaining web applications using React and Node.js.",
    openings: 10,
    eligibleInstitutes: [1, 2, 4],
  },
  {
    id: 2,
    title: "Data Analyst",
    company: "Infosys Limited",
    companyId: 2,
    companyLogo: "https://ui-avatars.com/api/?name=Infosys&background=1E88E5&color=fff&size=80",
    location: "Hyderabad",
    salary: "5–7 LPA",
    experience: "0–1 Years",
    lastDate: "2026-08-10",
    postedDate: "2026-07-03",
    status: "Published",
    skills: ["Python", "SQL", "Power BI"],
    eligibility: "Any Graduate – 65% and above",
    description:
      "Join Infosys as a Data Analyst and work with large datasets to drive business insights. Proficiency in Python and SQL is required.",
    openings: 20,
    eligibleInstitutes: [1, 2, 3, 4, 5],
  },
  {
    id: 3,
    title: "Cloud Engineer",
    company: "Wipro Technologies",
    companyId: 3,
    companyLogo: "https://ui-avatars.com/api/?name=Wipro&background=2E7D32&color=fff&size=80",
    location: "Pune",
    salary: "7–10 LPA",
    experience: "1–3 Years",
    lastDate: "2026-07-25",
    postedDate: "2026-06-28",
    status: "Approved",
    skills: ["AWS", "Azure", "Docker", "Kubernetes"],
    eligibility: "B.E / B.Tech – CS, IS – 70% and above",
    description:
      "We need a Cloud Engineer who can architect, implement, and maintain cloud infrastructure on AWS and Azure.",
    openings: 8,
    eligibleInstitutes: [1, 3],
  },
  {
    id: 4,
    title: "UI/UX Designer",
    company: "HCL Technologies",
    companyId: 4,
    companyLogo: "https://ui-avatars.com/api/?name=HCL&background=F9A825&color=fff&size=80",
    location: "Chennai",
    salary: "4–6 LPA",
    experience: "0–2 Years",
    lastDate: "2026-08-05",
    postedDate: "2026-07-05",
    status: "Pending",
    skills: ["Figma", "Adobe XD", "HTML", "CSS"],
    eligibility: "Any Graduate – 55% and above",
    description:
      "HCL is looking for a creative UI/UX Designer to design beautiful user interfaces and improve user experience.",
    openings: 5,
    eligibleInstitutes: [2, 4, 5],
  },
  {
    id: 5,
    title: "DevOps Engineer",
    company: "Capgemini India",
    companyId: 5,
    companyLogo: "https://ui-avatars.com/api/?name=Capgemini&background=D32F2F&color=fff&size=80",
    location: "Mumbai",
    salary: "8–12 LPA",
    experience: "2–4 Years",
    lastDate: "2026-07-20",
    postedDate: "2026-06-25",
    status: "Rejected",
    skills: ["Jenkins", "Git", "Linux", "Docker"],
    eligibility: "B.E / B.Tech – CS, IS – 65% and above",
    description:
      "Capgemini is hiring a DevOps Engineer to streamline CI/CD pipelines and manage production infrastructure.",
    openings: 12,
    eligibleInstitutes: [1, 2, 5],
  },
  {
    id: 6,
    title: "Full Stack Developer",
    company: "TechNova Solutions",
    companyId: 1,
    companyLogo: "https://ui-avatars.com/api/?name=TechNova&background=0F4C81&color=fff&size=80",
    location: "Bangalore",
    salary: "8–11 LPA",
    experience: "1–3 Years",
    lastDate: "2026-08-15",
    postedDate: "2026-07-07",
    status: "Published",
    skills: ["React", "Laravel", "MySQL", "REST APIs"],
    eligibility: "B.E / B.Tech – CS, IS – 65% and above",
    description:
      "Build scalable web applications as a Full Stack Developer using React on the frontend and Laravel on the backend.",
    openings: 7,
    eligibleInstitutes: [1, 2, 3, 4],
  },
];

// ─── STUDENTS ───────────────────────────────────────────────────────────────
export const students = [
  {
    id: 1,
    name: "Arjun Sharma",
    email: "arjun@email.com",
    phone: "9876543210",
    institute: "Aadya Institute",
    instituteId: 1,
    course: "B.E – Computer Science",
    batch: "2022–2026",
    skills: ["React", "Node.js", "MySQL"],
    profileCompletion: 85,
    resumeUrl: "/resumes/arjun_resume.pdf",
    status: "Active",
    cgpa: 8.2,
  },
  {
    id: 2,
    name: "Priya Rao",
    email: "priya@email.com",
    phone: "9123456789",
    institute: "PES College of Engineering",
    instituteId: 2,
    course: "B.E – Information Science",
    batch: "2022–2026",
    skills: ["Python", "SQL", "Machine Learning"],
    profileCompletion: 70,
    resumeUrl: "/resumes/priya_resume.pdf",
    status: "Active",
    cgpa: 7.8,
  },
  {
    id: 3,
    name: "Rohan Menon",
    email: "rohan@email.com",
    phone: "9988776655",
    institute: "Oxford College of Engineering",
    instituteId: 3,
    course: "B.E – Electronics",
    batch: "2021–2025",
    skills: ["Embedded C", "MATLAB", "PCB Design"],
    profileCompletion: 60,
    resumeUrl: "/resumes/rohan_resume.pdf",
    status: "Active",
    cgpa: 7.5,
  },
  {
    id: 4,
    name: "Sneha Patel",
    email: "sneha@email.com",
    phone: "9871234560",
    institute: "BMS College of Engineering",
    instituteId: 4,
    course: "B.E – Computer Science",
    batch: "2022–2026",
    skills: ["Java", "Spring Boot", "Angular"],
    profileCompletion: 90,
    resumeUrl: "/resumes/sneha_resume.pdf",
    status: "Active",
    cgpa: 8.9,
  },
  {
    id: 5,
    name: "Kiran Gowda",
    email: "kiran@email.com",
    phone: "9001234567",
    institute: "RV College of Engineering",
    instituteId: 5,
    course: "B.E – Mechanical",
    batch: "2021–2025",
    skills: ["AutoCAD", "SolidWorks", "ANSYS"],
    profileCompletion: 50,
    resumeUrl: "/resumes/kiran_resume.pdf",
    status: "Active",
    cgpa: 7.2,
  },
];

// ─── APPLICATIONS ────────────────────────────────────────────────────────────
export const applications = [
  {
    id: 1,
    studentId: 1,
    studentName: "Arjun Sharma",
    institute: "Aadya Institute",
    course: "B.E – Computer Science",
    email: "arjun@email.com",
    jobId: 1,
    jobTitle: "Software Developer",
    company: "TechNova Solutions",
    appliedDate: "2026-07-05",
    status: "Under Review",
    resumeUrl: "/resumes/arjun_resume.pdf",
  },
  {
    id: 2,
    studentId: 2,
    studentName: "Priya Rao",
    institute: "PES College of Engineering",
    course: "B.E – Information Science",
    email: "priya@email.com",
    jobId: 2,
    jobTitle: "Data Analyst",
    company: "Infosys Limited",
    appliedDate: "2026-07-06",
    status: "Shortlisted",
    resumeUrl: "/resumes/priya_resume.pdf",
  },
  {
    id: 3,
    studentId: 4,
    studentName: "Sneha Patel",
    institute: "BMS College of Engineering",
    course: "B.E – Computer Science",
    email: "sneha@email.com",
    jobId: 1,
    jobTitle: "Software Developer",
    company: "TechNova Solutions",
    appliedDate: "2026-07-07",
    status: "Under Review",
    resumeUrl: "/resumes/sneha_resume.pdf",
  },
  {
    id: 4,
    studentId: 1,
    studentName: "Arjun Sharma",
    institute: "Aadya Institute",
    course: "B.E – Computer Science",
    email: "arjun@email.com",
    jobId: 6,
    jobTitle: "Full Stack Developer",
    company: "TechNova Solutions",
    appliedDate: "2026-07-08",
    status: "Pending",
    resumeUrl: "/resumes/arjun_resume.pdf",
  },
];

// ─── EMAIL LOGS ──────────────────────────────────────────────────────────────
export const emailLogs = [
  {
    id: 1,
    company: "TechNova Solutions",
    job: "Software Developer",
    sentTo: "priya@technova.com",
    date: "2026-07-05",
    status: "Sent",
    applicantsCount: 3,
  },
  {
    id: 2,
    company: "Infosys Limited",
    job: "Data Analyst",
    sentTo: "rahul@infosys.com",
    date: "2026-07-06",
    status: "Sent",
    applicantsCount: 1,
  },
  {
    id: 3,
    company: "Wipro Technologies",
    job: "Cloud Engineer",
    sentTo: "anjali@wipro.com",
    date: "2026-07-07",
    status: "Failed",
    applicantsCount: 0,
  },
  {
    id: 4,
    company: "HCL Technologies",
    job: "UI/UX Designer",
    sentTo: "suresh@hcl.com",
    date: "2026-07-08",
    status: "Pending",
    applicantsCount: 2,
  },
];

// ─── DASHBOARD STATS ─────────────────────────────────────────────────────────
export const dashboardStats = {
  totalStudents: 9749,
  totalInstitutes: 2,
  totalCompanies: 47,
  totalJobs: 89,
  totalApplications: 3240,
  placedStudents: 9261,
};



// ─── TESTIMONIALS ────────────────────────────────────────────────────────────
export const testimonials = [
  {
    id: 1,
    name: "Sindhu K",
    role: "Computer Training • Coaching",
    quote: "Aadya Institute has been very useful for me as a coaching centre. Especially Sangeeta Ma’am’s classes are really great. She explains in multiple languages, making it very easy to understand. She teaches with a lot of patience and clears doubts no matter how many times we ask. Definitely, if anyone needs computer training, I suggest Aadya Institute!",
    avatar: "https://ui-avatars.com/api/?name=Sindhu+K&background=0F4C81&color=fff",
  },
  {
    id: 2,
    name: "Thejashri J",
    role: "Ramamurthy Nagar Branch",
    quote: "I have joined Aadya Institutions in Ramamurthy Nagar branch, learning from Sangeetha Ma'am. Her teaching style is very engaging. She is very patient, supportive, and always ready to help, both inside and outside the classroom. Because of her guidance, I feel more confident and interested in learning.",
    avatar: "https://ui-avatars.com/api/?name=Thejashri+J&background=1E88E5&color=fff",
  },
  {
    id: 3,
    name: "Diwakar Hegde",
    role: "Basics & MS Word Student",
    quote: "Aadya Institute of Technology is a good institute for learning computers and to build a good career. My teacher Sangeetha Ma'am is an excellent teacher with extraordinary teaching skills. I had a great opportunity to learn basics and MS Word under her guidance. Thankful to all faculty for supporting me!",
    avatar: "https://ui-avatars.com/api/?name=Diwakar+Hegde&background=2E7D32&color=fff",
  },
  {
    id: 4,
    name: "Keerthana R",
    role: "Excel, Word & PowerPoint",
    quote: "Excellent coaching centre! Teachers help students understand topics easily and make classes fun. Good facility and strong teaching skills. Great instructors and cooperative teachers for Excel, Word, PowerPoint and Computer Basics. Thank you to Sangeetha Ma'am and Madhumitha Ma'am!",
    avatar: "https://ui-avatars.com/api/?name=Keerthana+R&background=F9A825&color=fff",
  },
  {
    id: 5,
    name: "Satish N",
    role: "Diploma in Computer Application (DCA)",
    quote: "I recently enrolled in the Diploma in Computer Application. The trainer explained the concepts clearly, and after some hands-on practice, everything became much easier to understand. Thank you for the great instruction!",
    avatar: "https://ui-avatars.com/api/?name=Satish+N&background=D32F2F&color=fff",
  },
  {
    id: 6,
    name: "Madhushree S",
    role: "Power BI & Analytics",
    quote: "Amazing class and teacher! Would recommend everyone to attend. Professional program, the teaching is excellent, very supportive, and caring. Good facility and strong teaching skills for Power BI. Thank you so much Mageshwari Ma'am for teaching us!",
    avatar: "https://ui-avatars.com/api/?name=Madhushree+S&background=673AB7&color=fff",
  },
 
];

// ─── CURRENT STUDENT (mock logged-in) ────────────────────────────────────────
export const currentStudent = {
  id: 1,
  name: "Arjun Sharma",
  email: "arjun@email.com",
  phone: "9876543210",
  institute: "Aadya Institute",
  instituteId: 1,
  course: "B.E – Computer Science",
  batch: "2022–2026",
  skills: ["React", "Node.js", "MySQL", "Git"],
  profileCompletion: 85,
  resumeUrl: "/resumes/arjun_resume.pdf",
  cgpa: 8.2,
};
